from typing import AsyncIterator

from app.schemas import AlertDetails


## TODO actual LLM call implementation
class AlertSummary:
    def __init__(self):
        pass

    async def getSummary(self,alertdetails: AlertDetails) -> AsyncIterator[str]:
        messages = [
            "Alert A-10004567 was generated after the fraud detection engine identified unusual financial behavior on the customer’s account. The alert was triggered by a high-value international wire transfer that significantly exceeded the customer’s historical transaction average. The transaction was initiated from a newly registered device and originated from an IP address associated with a foreign region not previously linked to the customer profile. The transfer occurred outside of the customer’s normal activity hours and involved a beneficiary account that had been added only hours before the transaction was executed. Behavioral analytics detected multiple rapid login attempts prior to the successful authentication, and the device fingerprint differed from prior sessions. Although multi-factor authentication was successfully completed, the overall risk score calculated by the fraud model reached 0.92, exceeding the configured alert threshold and resulting in automatic alert creation.",
            "Upon generation, the alert was routed to the fraud operations review queue and assigned a medium-high severity level. Supporting transaction metadata, device attributes, session history, and geolocation enrichment were automatically attached to the case file. Historical analysis revealed that the customer typically performs low-value ACH transfers and rarely uses the wire channel. The last similar transaction had occurred more than two years prior. Network velocity checks indicated increased activity within a short timeframe, and anomaly detection systems flagged the unusual timing pattern. Cross-border compliance screening was triggered due to the receiving bank’s jurisdiction, and AML monitoring checks were executed as part of the enrichment workflow.",
            "An assigned fraud analyst initiated case review within minutes of alert creation. The analyst examined the customer’s KYC profile, which was found to be up to date, with no recent address or contact information changes recorded. Previous alert history showed three low-risk alerts that had all been resolved as false positives. Device risk indicators suggested moderate anomaly but not confirmed compromise. The analyst reviewed login session data, including browser version, operating system, and device identifiers, and noted that the current device had not been previously registered. No sanctions or watchlist matches were returned during screening. Audit trails and session metadata were preserved for regulatory and compliance review purposes.",
            "The analyst proceeded to contact the customer through registered communication channels. The first call attempt went unanswered, and a secure voicemail was left requesting transaction confirmation. A secure message was also delivered through the online banking portal. Within one hour, the customer responded and confirmed initiating the transaction while traveling internationally. The customer explained that a new personal laptop had recently been purchased and used for the transfer. Travel details provided by the customer aligned with the IP geolocation captured in system logs. The customer verified the beneficiary relationship and provided supporting context for the urgent transfer request.",
            "Based on the customer’s confirmation and supporting evidence, the analyst determined that the transaction was legitimate. The fraud risk level was downgraded, and the alert status was updated to resolved. Documentation of the customer interaction, verification steps, and review notes were attached to the case file. No account restrictions were applied, and the transaction was allowed to proceed without interruption. The case was closed within the established service level agreement window, and feedback was submitted to the fraud model monitoring team to improve future behavioral scoring accuracy.",
            "All relevant alert lifecycle events were logged in the monitoring dashboard, and performance metrics indicated normal system operation throughout processing. The alert record remains archived for audit and analytics purposes, ensuring traceability for future reviews. No suspicious activity report was required, and compliance teams were informed of case closure. The customer was advised to register new devices proactively and to notify the bank before international travel to prevent future alerts. Continued monitoring will remain in place for the account, and system health checks confirmed stable performance during the entire alert handling process."
        ]

        for msg in messages:
            yield msg